# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sdf-group-rubin
#   namespace: devel-transfer-embargo
# spec:
#   storageClassName: sdf-group-rubin
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sdf-data-rubin
#   namespace: devel-transfer-embargo
# spec:
#   storageClassName: sdf-data-rubin
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
# ---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-transfer-embargo
  namespace: devel-transfer-embargo
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: transfer-embargo-container
              image: "ghcr.io/lsst-dm/transfer-embargo-helloworld:latest"
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
              volumeMounts:
                - name: sdf-group-rubin
                  mountPath: /sdf/group/rubin
                - name: sdf-data-rubin
                  mountPath: /sdf/data/rubin
          volumes:
            - name: sdf-group-rubin
              persistentVolumeClaim:
                claimName: sdf-group-rubin
            - name: sdf-data-rubin
              persistentVolumeClaim:
                claimName: sdf-data-rubin
          restartPolicy: OnFailure

