ARG STACKVER=w_2025_16
FROM ghcr.io/lsst/scipipe:al9-${STACKVER}

# Copy code and configuration
ENV SWDIR="/opt/lsst/transfer_embargo"
COPY src/transfer_zip.py src/transfer_zip.sh "$SWDIR"

# Define the environment variables
ENV TMPDIR="/tmp"
ENV LOGNAME="rubinmgr"
ENV TRANSFER_CONFIG="/etc/lsst/config_raw.yaml"
ENV WINDOW="35min"
ENV DEST="/sdf/data/rubin/lsstdata/offline/instrument/"
ENV RUCIO="-r SLAC_RAW_DISK -s raw"
ENV FROMREPO="embargo"
ENV TOREPO="/repo/main"
# Also need RUCIO_CONFIG, DAF_BUTLER_REPOSITORY_INDEX, and credentials
# LOGDIR is optional to store copies of the logs (which also go to stdout)

CMD "$SWDIR/transfer_zip.sh"
