# Dockerfile

FROM python:3.10

ADD helloworld.py .

CMD ["python", "-m", "pip", "install", "argparse"]

# CMD ["python", "-u", "./helloworld.py", "--num", "$NUM"]

CMD ["/bin/sh", "-c", "python ./helloworld.py --num $NUM"]

# CMD echo 'Hi its me, Im the problem its me'

