# Dockerfile
FROM ghcr.io/lsst/scipipe:al9-w_2025_15

# Copy code and configuration
COPY src/transfer_zip.py /opt/lsst/transfer_embargo/

# Set the working directory
WORKDIR /opt/lsst/transfer_embargo

# Define the environment variables
ENV FROMREPO "embargo"
ENV TOREPO "/repo/main"
ENV WINDOW "1.1hr"
ENV DEST "/sdf/data/rubin/lsstdata/offline/instrument/"
ENV RUCIO "-r SLAC_RAW_DISK -s raw"

CMD ["bash", "-c", "source /opt/lsst/loadLSST.sh; setup lsst_distrib; umask 027; python transfer_zip.py -C /etc/lsst/config_raw.yaml --window \"$WINDOW\" -d \"$DEST\" $RUCIO \"$FROMREPO\" \"$TOREPO\""]
