name: build transfer-raw container

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Build
        uses: lsst-sqre/build-and-push-to-ghcr@v1
        with:
            image: lsst-dm/transfer-raw
            github_token: ${{ secrets.GITHUB_TOKEN }}
            dockerfile: Dockerfile.raw
