name: test
on:
  push:
    branches:
    - main
    - tickets/DM-40268
    tags:
    - v*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Setup python 3.10
      uses: actions/setup-python@v2
      with:
          python-version: "3.10"
    - name: docker build
      run: |
        docker build . -f Dockerfile_simple
    - name: Log in to Github container registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" |docker login ghcr.io -u $ --password-stdin
    - name: Install dependencies
      run: |
       python -m ensurepip
       python -m pip install lsst-daf-butler
    - name: Test with pytest
      run: |
       cd ./tests
       python test_move_embargo_args.py

