name: test
on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: docker build
      run: |
        docker build . -f Dockerfile 
    - name: Test with unittest
      run: |
       cd ./tests
       python test_move_embargo_args.py
