name: test
on:
  push:
    branches:
    # - main
    - tickets/DM-41033
    tags:
    - v*
  pull_request:

env:
  PROGRAM_NAME: transfer-embargo
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Setup python 3.11
      uses: actions/setup-python@v4
      with:
          python-version: "3.11"
    - name: Install dependencies
      run: |
          curl -OL https://ls.st/lsstinstall
          chmod u+x lsstinstall
          ./lsstinstall -T w_2023_50
          source loadLSST.sh
          eups distrib install -t w_2023_50 obs_lsst
          curl -sSL https://raw.githubusercontent.com/lsst/shebangtron/main/shebangtron | python

    - name: Run tests
      run: |
          source loadLSST.sh
          setup obs_lsst
          cd ./tests
          python test_move_embargo_args.py
    # - name: docker build
    #   run: |
    #     docker build . \
    #     --tag $PROGRAM_NAME
    # - name: Log in to Github container registry
    #   run: echo "${{ secrets.GITHUB_TOKEN }}" |docker login ghcr.io -u $ --password-stdin
    # - name: Push images
    #   run: |
    #     PROGRAM_ID=ghcr.io/${{ github.repository_owner }}/$PROGRAM_NAME
    #     if [[ "${{ github.ref }}" == "refs/pull/"* ]]; then
    #       VERSION=$(echo "${{ github.head_ref }}" | sed -e 's|.*/||')
    #     elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
    #       VERSION=$(echo "${{ github.ref_name }}" | sed -e 's|^v||')
    #     else
    #       VERSION=latest
    #     fi
    #     echo VERSION=$VERSION
    #     echo PROGRAM_ID=$PROGRAM_ID
    #     docker tag $PROGRAM_NAME $PROGRAM_ID:$VERSION
    #     docker push $PROGRAM_ID:$VERSION
